--------------------------------------------------------
--  Arquivo criado - quinta-feira-maio-18-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMINISTRADOR
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME" VARCHAR2(80 BYTE), 
	"SENHA" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONSULTAS
--------------------------------------------------------

  CREATE TABLE "CONSULTAS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PROTOCOLO" VARCHAR2(50 BYTE), 
	"DATA_CONSULTA" TIMESTAMP (6), 
	"TIPO_CONSULTA" VARCHAR2(20 BYTE), 
	"CONSULTA_RETORNO" NUMBER(*,0), 
	"PACIENTE_ID" NUMBER(*,0), 
	"RECEPCIONISTA_ID" NUMBER(*,0), 
	"MEDICO_ID" NUMBER(*,0), 
	"CHEGADA_AT" TIMESTAMP (6), 
	"ATENDIMENTO_AT" TIMESTAMP (6), 
	"OBSERVACAO" VARCHAR2(250 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIAS
--------------------------------------------------------

  CREATE TABLE "DIAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DIA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JORNADAS
--------------------------------------------------------

  CREATE TABLE "JORNADAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CREATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	"MEDICO_ID" NUMBER, 
	"DIA_ID" NUMBER, 
	"TURNO_ID" NUMBER, 
	"IS_FOLGA" CHAR(1 BYTE) DEFAULT ON NULL '0'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDICOS
--------------------------------------------------------

  CREATE TABLE "MEDICOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CREATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	"CRM" VARCHAR2(15 BYTE), 
	"IS_ATIVO" CHAR(1 BYTE) DEFAULT ON NULL '0', 
	"NOME" VARCHAR2(80 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE), 
	"SENHA" VARCHAR2(80 BYTE), 
	"TELEFONE" VARCHAR2(20 BYTE), 
	"ESPECIALIDADE" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PACIENTES
--------------------------------------------------------

  CREATE TABLE "PACIENTES" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME" VARCHAR2(80 BYTE), 
	"DATA_NASCIMENTO" DATE, 
	"RESPONSAVEL" VARCHAR2(80 BYTE), 
	"CPF" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"CIDADE" VARCHAR2(80 BYTE), 
	"ESTADO" VARCHAR2(30 BYTE), 
	"CEP" VARCHAR2(30 BYTE), 
	"ENDERECO" VARCHAR2(100 BYTE), 
	"TELEFONE" VARCHAR2(20 BYTE), 
	"TELEFONE2" VARCHAR2(20 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLANOS_SAUDE
--------------------------------------------------------

  CREATE TABLE "PLANOS_SAUDE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CNPJ" VARCHAR2(20 BYTE), 
	"RAZAO_SOCIAL" VARCHAR2(80 BYTE), 
	"ID_PACIENTE" NUMBER(*,0), 
	"DESCRICAO" VARCHAR2(100 BYTE), 
	"ESTA_ATIVO" CHAR(1 BYTE) DEFAULT ON NULL '0', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECEPCIONISTAS
--------------------------------------------------------

  CREATE TABLE "RECEPCIONISTAS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME" VARCHAR2(80 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"SENHA" VARCHAR2(100 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TURNOS
--------------------------------------------------------

  CREATE TABLE "TURNOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"E1" TIMESTAMP (6), 
	"S1" TIMESTAMP (6), 
	"E2" TIMESTAMP (6), 
	"S2" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMINISTRADOR
SET DEFINE OFF;
Insert into ADMINISTRADOR (ID,NOME,SENHA,EMAIL,CREATED_AT,UPDATED_AT) values ('1','admin','admin','adm@clinica.com',to_timestamp('18/05/23 20:19:25','DD/MM/RR HH24:MI:SS'),to_timestamp('18/05/23 20:19:25','DD/MM/RR HH24:MI:SS'));
REM INSERTING into CONSULTAS
SET DEFINE OFF;
REM INSERTING into DIAS
SET DEFINE OFF;
REM INSERTING into JORNADAS
SET DEFINE OFF;
REM INSERTING into MEDICOS
SET DEFINE OFF;
REM INSERTING into PACIENTES
SET DEFINE OFF;
Insert into PACIENTES (ID,NOME,DATA_NASCIMENTO,RESPONSAVEL,CPF,EMAIL,CIDADE,ESTADO,CEP,ENDERECO,TELEFONE,TELEFONE2,CREATED_AT,UPDATED_AT) values ('1','Lohane Vekanandre Stefany Smith Bueno',to_date('09/10/00 00:00:00','DD/MM/RR HH24:MI:SS'),null,'69842564398','lohany@bol.com','fortaleza','ceara',null,'beco da poeira, 133, centro','5585985552255',null,to_timestamp('18/05/23 20:26:28','DD/MM/RR HH24:MI:SS'),to_timestamp('18/05/23 20:26:28','DD/MM/RR HH24:MI:SS'));
REM INSERTING into PLANOS_SAUDE
SET DEFINE OFF;
Insert into PLANOS_SAUDE (ID,CNPJ,RAZAO_SOCIAL,ID_PACIENTE,DESCRICAO,ESTA_ATIVO,CREATED_AT,UPDATED_AT) values ('1','66878965192','happyVida planos','1','plano categoria A','1',to_timestamp('18/05/23 20:29:44','DD/MM/RR HH24:MI:SS'),to_timestamp('18/05/23 20:29:44','DD/MM/RR HH24:MI:SS'));
REM INSERTING into RECEPCIONISTAS
SET DEFINE OFF;
REM INSERTING into TURNOS
SET DEFINE OFF;
Insert into TURNOS (ID,E1,S1,E2,S2) values ('1',to_timestamp('01/01/00 07:00:00','DD/MM/RR HH24:MI:SS'),to_timestamp('01/01/00 12:00:00','DD/MM/RR HH24:MI:SS'),to_timestamp('01/01/00 14:00:00','DD/MM/RR HH24:MI:SS'),to_timestamp('01/01/00 16:20:00','DD/MM/RR HH24:MI:SS'));
--------------------------------------------------------
--  Constraints for Table ADMINISTRADOR
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDICOS
--------------------------------------------------------

  ALTER TABLE "MEDICOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" MODIFY ("CRM" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" MODIFY ("IS_ATIVO" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" MODIFY ("TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" MODIFY ("ESPECIALIDADE" NOT NULL ENABLE);
  ALTER TABLE "MEDICOS" ADD CONSTRAINT "CK_ISACTIVE" CHECK ("IS_ATIVO"='0' OR "IS_ATIVO"='1') ENABLE;
  ALTER TABLE "MEDICOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSULTAS
--------------------------------------------------------

  ALTER TABLE "CONSULTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CONSULTAS" MODIFY ("PROTOCOLO" NOT NULL ENABLE);
  ALTER TABLE "CONSULTAS" MODIFY ("DATA_CONSULTA" NOT NULL ENABLE);
  ALTER TABLE "CONSULTAS" MODIFY ("TIPO_CONSULTA" NOT NULL ENABLE);
  ALTER TABLE "CONSULTAS" MODIFY ("PACIENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "CONSULTAS" MODIFY ("RECEPCIONISTA_ID" NOT NULL ENABLE);
  ALTER TABLE "CONSULTAS" MODIFY ("MEDICO_ID" NOT NULL ENABLE);
  ALTER TABLE "CONSULTAS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CONSULTAS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CONSULTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIAS
--------------------------------------------------------

  ALTER TABLE "DIAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DIAS" MODIFY ("DIA" NOT NULL ENABLE);
  ALTER TABLE "DIAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TURNOS
--------------------------------------------------------

  ALTER TABLE "TURNOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TURNOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JORNADAS
--------------------------------------------------------

  ALTER TABLE "JORNADAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JORNADAS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "JORNADAS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "JORNADAS" MODIFY ("MEDICO_ID" NOT NULL ENABLE);
  ALTER TABLE "JORNADAS" MODIFY ("DIA_ID" NOT NULL ENABLE);
  ALTER TABLE "JORNADAS" MODIFY ("TURNO_ID" NOT NULL ENABLE);
  ALTER TABLE "JORNADAS" MODIFY ("IS_FOLGA" NOT NULL ENABLE);
  ALTER TABLE "JORNADAS" ADD CONSTRAINT "CK_ISDAYOFF" CHECK ("IS_FOLGA"='0' OR "IS_FOLGA"='1') ENABLE;
  ALTER TABLE "JORNADAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PACIENTES
--------------------------------------------------------

  ALTER TABLE "PACIENTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" MODIFY ("DATA_NASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" MODIFY ("CPF" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" MODIFY ("CIDADE" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" MODIFY ("ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" MODIFY ("TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "PACIENTES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANOS_SAUDE
--------------------------------------------------------

  ALTER TABLE "PLANOS_SAUDE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PLANOS_SAUDE" MODIFY ("CNPJ" NOT NULL ENABLE);
  ALTER TABLE "PLANOS_SAUDE" MODIFY ("ID_PACIENTE" NOT NULL ENABLE);
  ALTER TABLE "PLANOS_SAUDE" MODIFY ("ESTA_ATIVO" NOT NULL ENABLE);
  ALTER TABLE "PLANOS_SAUDE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "PLANOS_SAUDE" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "PLANOS_SAUDE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RECEPCIONISTAS
--------------------------------------------------------

  ALTER TABLE "RECEPCIONISTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RECEPCIONISTAS" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "RECEPCIONISTAS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "RECEPCIONISTAS" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "RECEPCIONISTAS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RECEPCIONISTAS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RECEPCIONISTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSULTAS
--------------------------------------------------------

  ALTER TABLE "CONSULTAS" ADD CONSTRAINT "CONSULTAS_PACIENTES_FK" FOREIGN KEY ("PACIENTE_ID")
	  REFERENCES "PACIENTES" ("ID") ENABLE;
  ALTER TABLE "CONSULTAS" ADD CONSTRAINT "CONSULTAS_RECEPCIONISTA_FK" FOREIGN KEY ("RECEPCIONISTA_ID")
	  REFERENCES "RECEPCIONISTAS" ("ID") ENABLE;
  ALTER TABLE "CONSULTAS" ADD CONSTRAINT "CONSULTAS_MEDICO_FK" FOREIGN KEY ("MEDICO_ID")
	  REFERENCES "MEDICOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANOS_SAUDE
--------------------------------------------------------

  ALTER TABLE "PLANOS_SAUDE" ADD CONSTRAINT "PLANOS_SAUDE_FK" FOREIGN KEY ("ID")
	  REFERENCES "PACIENTES" ("ID") ENABLE;
